# Generated by Django 6.0.6 on 2026-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('setor', models.CharField(choices=[('CT', 'CONTABILIDADE'), ('ST', 'SECRETARIA'), ('CF', 'COMPRAS E FINANCEIRO'), ('CO', 'COORDENAÇÃO'), ('RA', 'REUNIÃO ANEXO'), ('AN', 'ANEXO'), ('TC', 'TÉCNICOS'), ('RC', 'RECEPÇÃO'), ('OT', 'OUTROS')], default='ST', max_length=2)),
                ('prioridade', models.CharField(choices=[('AL', 'ALTA'), ('ME', 'MEDIA'), ('BA', 'BAIXA')], default='BA', max_length=2)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField()),
            ],
        ),
    ]
